apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: tomcat-app
spec:
  selector:
    app: tomcat
  type: LoadBalancer
  ports:
  - port: 80        # exposed externally
    targetPort: 8080
    protocol: TCP

